id: ACD575115
title: 'The Garland of Utpala Flowers: A Prayer to the Masters of the Lineage of Zabtik
  Drolchok'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.979627
  last_modified_at: 2022-02-28 23:58:45.979630
