id: ACD575115
title: Prayer to Root and Lineage Masters, and the Assembly of Deity, Ḍākinīs and
  Dharma Protectors of the Sakya Lineage
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.959334
  last_modified_at: 2022-02-28 23:58:45.959336
