id: ACD575115
title: 'Music to Delight the Ḍākinī: A Praise to the Deathless Mandāravā'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.948317
  last_modified_at: 2022-02-28 23:58:45.948321
