id: ACD575115
title: In Praise of Jamyang Khyentse Wangpo
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.941862
  last_modified_at: 2022-02-28 23:58:45.941864
