id: ACD575115
title: 'The Rain of Virtue and Goodness: A Short Practice for Consecrating Representations
  of Enlightened Body, Speech and Mind'
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.994531
  last_modified_at: 2022-02-28 23:58:45.994535
