id: ACD575115
title: The General Visualization for Prayers to Guru Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.980979
  last_modified_at: 2022-02-28 23:58:45.980981
