id: ACD575115
title: The Single-Form Daily Practice from Chimé Pakmé Nyingtik (The Heart Essence
  of the Sublime Lady of Immortality)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:46.000963
  last_modified_at: 2022-02-28 23:58:46.000966
