id: ACD575115
title: 'Song and Dance to Delight the Ḍākas and Ḍākinīs: An Aspiration for the Sixfold
  Satisfaction of the Maṇḍala of the Feast-Gathering'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.965793
  last_modified_at: 2022-02-28 23:58:45.965796
