id: ACD575115
title: Supplement to the Omniscient Ngorchen Kunga Zangpo’s Prayer to the Lineage
  of Parting from the Four Attachments
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.968659
  last_modified_at: 2022-02-28 23:58:45.968662
