id: ACD575115
title: 'The Sweet-Sounding Song that Fulfils All Aims: A Prayer to Noble Tārā Combined
  with Her Root Mantra'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:46.002547
  last_modified_at: 2022-02-28 23:58:46.002549
