id: ACD575115
title: 'Source of Magnificent Blessing: A Prayer to the Lineage of the Secret Practice
  of the Great Compassionate One, Natural Liberation of Suffering'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.967113
  last_modified_at: 2022-02-28 23:58:45.967115
