id: ACD575115
title: A Brief Practice of Consecrating Amṛta for the Vidyādhara Assembly
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.916814
  last_modified_at: 2022-02-28 23:58:45.916818
