id: ACD575115
title: 'Moonlight of Pacifying Amṛta: A Daily Visualization and Recitation for the
  Dispeller of All Samaya Corruptions and Pollutions'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.946084
  last_modified_at: 2022-02-28 23:58:45.946087
