id: ACD575115
title: Short Tsok Offering to the Powerful Lady Kurukullā
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.964245
  last_modified_at: 2022-02-28 23:58:45.964248
