id: ACD575115
title: The Visualization of the Four Goddesses of the Great Compassionate One, Natural
  Liberation of Suffering
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:46.009215
  last_modified_at: 2022-02-28 23:58:46.009218
