id: ACD575115
title: A Brief Practice of Paying Homage and Making Offerings to the Sixteen Elders
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.919837
  last_modified_at: 2022-02-28 23:58:45.919840
