id: ACD575115
title: Prayer to Thangtong Gyalpo
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.961091
  last_modified_at: 2022-02-28 23:58:45.961094
