id: ACD575115
title: 'The Excellent Path to Enlightenment: A Brief Practice of the Preliminaries'
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.975798
  last_modified_at: 2022-02-28 23:58:45.975801
