id: ACD575115
title: Prayer to the Siddha Virūpa
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.962310
  last_modified_at: 2022-02-28 23:58:45.962312
