id: ACD575115
title: Activities for Uncovering Primordial Wisdom from the Chimé Pakmé Nyingtik,
  ‘The Heart Essence of the Sublime Lady of Immortality’
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.933641
  last_modified_at: 2022-02-28 23:58:45.933644
