id: ACD575115
title: 'Bestower of the Light of Intelligence: A Prayer to the Lineage of the Profound
  Sādhana Based Upon the Praise to Venerable Mañjughoṣa'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.934984
  last_modified_at: 2022-02-28 23:58:45.934986
