id: ACD575115
title: Words of Jamyang Khyentse
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:46.021170
  last_modified_at: 2022-02-28 23:58:46.021172
