id: ACD575115
title: 'The Heart of Blessings: A Brief Anthology of Prayers to Guru Rinpoche and
  the Twenty-Five Disciples, the King and Subjects'
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.983009
  last_modified_at: 2022-02-28 23:58:45.983012
