id: ACD575115
title: Prayer to Khyentse Wangpo, Kongtrul and Chokgyur Lingpa
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.958258
  last_modified_at: 2022-02-28 23:58:45.958262
