id: ACD575115
title: 'A Shower of Great Bliss: A Lineage Prayer for the Guru Yoga based on Vajrasattva'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.931885
  last_modified_at: 2022-02-28 23:58:45.931888
