id: ACD575115
title: 'Harmonious Clouds of Sublime and Lasting Bliss: A Vajra Song for the Tsok
  Feast Offering to Venerable and Exalted Vajrayoginī'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.940773
  last_modified_at: 2022-02-28 23:58:45.940776
