id: ACD575115
title: 'The Vajra Lute: A Brief Fulfilment for the Guru Practice of VidyÄdhara-Assembly'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:46.007754
  last_modified_at: 2022-02-28 23:58:46.007756
