id: ACD575115
title: 'Wish-Fulfilling Feast of Siddhis: An Aspiration Prayer to Orgyen Rinpoche,
  the Precious Master of Oddiyana'
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:46.018222
  last_modified_at: 2022-02-28 23:58:46.018225
