id: ACD575115
title: The Essential Activity Manual for the Awesome Ones’ Assembly, the Heart Practice
  of Vidyādharas, from the Heart Essence of the Vast Expanse
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.973739
  last_modified_at: 2022-02-28 23:58:45.973742
