id: ACD575115
title: 'Essence of Accomplishment: A Concise Feast-Offering to Noble Tārā'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.936922
  last_modified_at: 2022-02-28 23:58:45.936924
