id: ACD575115
title: 'The Flower of Faith: A Prayer to the Twenty-Five Founders of Buddha''s Teachings
  in Tibet'
type: translation
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.977843
  last_modified_at: 2022-02-28 23:58:45.977845
