id: ACD575115
title: 'The Chariot of the Vidyādharas: An Aspiration Prayer for Travelling to the
  Realm of Lotus Light'
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.971519
  last_modified_at: 2022-02-28 23:58:45.971522
