id: ACD575115
title: 'Turning Back Obstacles and Adverse Circumstances: A Prayer to Orgyen Rinpoche,
  Embodiment of All Sources of Refuge'
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:46.012937
  last_modified_at: 2022-02-28 23:58:46.012941
