id: ACD575115
title: A Brief Prayer to the Precious Master Padmākara for Swiftly Fulfilling Wishes
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.921608
  last_modified_at: 2022-02-28 23:58:45.921610
