id: ACD575115
title: Concise Seven-Heap Maṇḍala Offering
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.935934
  last_modified_at: 2022-02-28 23:58:45.935936
