id: ACD575115
title: 'A Shortcut to the Siddhi of Immortality: Guru Yoga of Union with the Three
  Deities of Long Life'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.930042
  last_modified_at: 2022-02-28 23:58:45.930045
