id: ACD575115
title: Prayer to Chökyi Wangpo, the Bodhisattva and Tamer of Beings
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.952696
  last_modified_at: 2022-02-28 23:58:45.952699
