id: ACD575115
title: Supplication to Lord Buddha together with the Sixteen Arhats
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.969749
  last_modified_at: 2022-02-28 23:58:45.969752
