id: ACD575115
title: 'The Single Mudrā: A Daily Practice for the Awesome Ones’ Assembly (Palchen
  Düpa), the Heart Practice of the Awareness-Holders'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.999931
  last_modified_at: 2022-02-28 23:58:45.999933
