id: ACD575115
title: The Twenty-Eight Commitments
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:46.005217
  last_modified_at: 2022-02-28 23:58:46.005220
