id: ACD575115
title: 'Fast Track to Happiness and Peace: A Very Brief Meditation and Recitation
  of the Medicine Buddha'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.937943
  last_modified_at: 2022-02-28 23:58:45.937946
