id: ACD575115
title: 'A Beautiful and Wondrous Udumbara Garland: A Supplication and Summary of the
  Chronicles of Padma, The Life and Liberation of the Precious Guru of Uḍḍiyāna'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.912963
  last_modified_at: 2022-02-28 23:58:45.912972
