id: ACD575115
title: 'A Glorious Garland of the Two Accomplishments: An Abridged Feast-Offering
  for the Female Practice of the Ḍākinī'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.922659
  last_modified_at: 2022-02-28 23:58:45.922662
