id: ACD575115
title: 'The Melody of Complete Accomplishment: A Prayer to Those Praised as Ornaments
  of the Practice Lineage'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.991398
  last_modified_at: 2022-02-28 23:58:45.991400
