id: ACD575115
title: 'Wisdom''s Bestowal: A Way to Accumulate the Recitation of the Tantra ''Chanting
  the Names of Mañjuśrī'' (Mañjuśrī Nāma Saṃgīti)'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:46.014921
  last_modified_at: 2022-02-28 23:58:46.014924
