id: ACD575115
title: Offering the Eight Auspicious Substances and Seven Emblems of Royalty
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:58:45.951019
  last_modified_at: 2022-02-28 23:58:45.951022
